name: ci
on: [push]

jobs:
  #lint:
  #  name: lint
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: go setup
  #    uses: actions/setup-go@v1
  #    with: { go-version: '1.13' }
  #  - name: clone
  #    uses: actions/checkout@v1
  #    with: { fetch-depth: 1 }
  #  - name: install linter
  #    run: go get -u golang.org/x/lint/golint
  #  - name: lint
  #    run: $HOME/bin/golint ./...

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.13', '1.12']
    steps:
      - name: go setup
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: clone
        uses: actions/checkout@v1
        with: { fetch-depth: 1 }
      - name: test
        run: go test -count 1 -v ./...
